server:
  port: 8080


spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/communitymanagement?characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效

thymeleaf:
  prefix: classpath:/WEB-INF/jsp
  suffix: .jsp

mybatis:
  type-aliases-package: com.pojo
  mapper-locations: classpath*:com/mapping/*.xml
  logging:
    level:
    com.mapper: debug



